"""repo and user table changes

Revision ID: 43f938bddb7e
Revises: 28b006a572c5
Create Date: 2025-03-10 10:27:32.553891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43f938bddb7e'
down_revision = '28b006a572c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pushed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_called_repos', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('latest_etag_repos', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('latest_etag_repos')
        batch_op.drop_column('last_called_repos')

    with op.batch_alter_table('repos', schema=None) as batch_op:
        batch_op.drop_column('pushed_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
