"""empty message

Revision ID: dd445d8109b3
Revises: 43f938bddb7e
Create Date: 2025-03-15 18:03:49.568570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd445d8109b3'
down_revision = '43f938bddb7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commits_etag', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('commits_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repos', schema=None) as batch_op:
        batch_op.drop_column('commits_data')
        batch_op.drop_column('commits_etag')

    # ### end Alembic commands ###
